#Deps
FROM node:24-alpine3.22 AS deps
WORKDIR /usr/src/app
COPY package.json ./
COPY yarn.lock ./
RUN yarn install

#Build
FROM node:24-alpine3.22 AS build
WORKDIR /usr/src/app
COPY --from=deps /usr/src/app/node_modules ./node_modules
COPY . .
RUN npx prisma generate
RUN yarn build
RUN yarn install --frozen-lockfile --production && yarn cache clean

#Prod
FROM node:24-alpine3.22 AS prod
WORKDIR /usr/src/app
COPY --from=build /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/generated ./generated
COPY --from=build /usr/src/app/prisma/dev.db ./prisma/dev.db
ENV NODE_ENV=production
USER node
EXPOSE 3000
CMD [ "node", "dist/src/main.js" ]